# Generated by Django 2.2.5 on 2019-09-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fetures',
            field=models.TextField(blank=True, null=True),
        ),
    ]
