# Generated by Django 2.2.5 on 2019-09-17 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_fetures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='fetures',
            new_name='features',
        ),
    ]
